/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ashvin' at '3/1/16 10:04 AM' with Gradle 2.6
 *
 * @author Ashvin, @date 3/1/16 10:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
